#!/usr/bin/expect -f
set timeout -1
spawn ssh -o StrictHostKeyChecking=no uid1102122@shell.r5.websupport.sk -p28035
expect "password:"
send "247fa026ba\r"
expect "$ "
send "cd cstudios.sk/sub/projektyerik\r"
expect "$ "
send "php -r \"require 'api/db.php'; print_r(\\\$pdo->query('SELECT table_name FROM information_schema.tables WHERE table_name = \\\'project_activities\\\'')->fetchAll());\"\r"
expect "$ "
send "exit\r"
expect eof
