#!/usr/bin/expect -f
set timeout -1
spawn ssh -o StrictHostKeyChecking=no uid1102122@shell.r5.websupport.sk -p25076
expect "password:"
send "56b715781e\r"
expect "$ "
send "cd cstudios.sk/sub/projektyerik\r"
expect "$ "
send "echo '{\"require\":{\"cstudios-slovakia/projekty\":\"1.9.20\"}}' > composer.json\r"
expect "$ "
send "composer require cstudios-slovakia/projekty:1.9.20\r"
expect "$ "
send "php vendor/cstudios-slovakia/projekty/publish.php\r"
expect "$ "
send "exit\r"
expect eof
