#!/usr/bin/expect -f
set timeout -1
set host "uid1102122@shell.r5.websupport.sk"
set password "793921881f"
set port "28865"

spawn ssh -o StrictHostKeyChecking=no -p $port $host
expect {
    "*assword:*" {
        send "$password\r"
        exp_continue
    }
    "$ "
}

send "cd cstudios.sk/sub/projektstaging && composer update\r"
expect "$ "

send "cd frontend && npm install && npm run build\r"
expect "$ "

send "exit\r"
expect eof
