#!/usr/bin/expect -f
set password "c408c0abc6"
set host "uid2136377@shell.r2.websupport.sk"
set port "27900"
spawn ssh -p $port -o StrictHostKeyChecking=no $host
expect "password:"
send "$password\r"
expect -re {.*[\$#] }
send "cd ~/softwaresolutions.sk/sub/projekt && sed -i 's/v1.7.20/v1.7.21/g' composer.json\r"
expect -re {.*[\$#] }
send "composer update\r"
expect -re {.*[\$#] }
send "exit\r"
expect eof
