#!/usr/bin/expect -f
set timeout 300
set password "79b90302f6"
set user "uid1102122"
set host "shell.r5.websupport.sk"
set port "26171"

spawn ssh -p $port -o StrictHostKeyChecking=no $user@$host "cd cstudios.sk/sub/projektyerik && rm -rf vendor/cstudios-slovakia/projekty && composer clear-cache && composer update cstudios-slovakia/projekty --no-interaction"
expect "password:"
send "$password\r"
expect eof
